# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 04:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wsse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wsseevent',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
